server:
  port: 8010

spring:
  datasource:
    url: jdbc:mysql://172.17.0.4:3306/shop?createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    initialization-mode: always
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
logging:
  level:
    org:
      hibernate:
        type: trace

sso:
  check: http://localhost:8002/sso/check
  auth:  http://localhost:8002/sso/autenticate